# Generated by Django 5.1.3 on 2024-11-22 10:12

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(error_messages={'uniqe': ' a user with this username '}, help_text='Required , 35 characters or fewer , starting with Letter , digit or number', max_length=35, unique=True, validators=[django.core.validators.RegexValidator('^[a-z A-Z][a-z A-Z 0-9 _\\.]+$)', 'Enter a valid username starting with a-z , this value may contain letters , numbers and under score character')], verbose_name='nickname')),
                ('phone_number', models.BigIntegerField(blank=True, error_messages={'uiqe': 'a user with tis mobile number exist'}, null=True, unique=True, validators=[django.core.validators.RegexValidator('^989[0-3 , 9/\\d{8}$', 'enter a valid number')], verbose_name='mobile number')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'users',
            },
        ),
    ]
