# Generated by Django 5.1.3 on 2024-11-23 07:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone_number',
            field=models.BigIntegerField(blank=True, error_messages={'unique': 'a user with tis mobile number exist'}, null=True, unique=True, validators=[django.core.validators.RegexValidator('^989[0-3 , 9/\\d{8}$', 'enter a valid number')], verbose_name='mobile number'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(error_messages={'unique': ' a user with this username '}, help_text='Required , 35 characters or fewer , starting with Letter , digit or number', max_length=35, unique=True, validators=[django.core.validators.RegexValidator('^[a-z A-Z][a-z A-Z 0-9 _\\.]+$)', 'Enter a valid username starting with a-z , this value may contain letters , numbers and under score character')], verbose_name='nickname'),
        ),
    ]
